INSERT INTO videos (title, link, user_id, category_id)
VALUES
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 1, 1),
('JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour [2020]', 'https://www.youtube.com/watch?v=OWEC-KSdmHw', 1, 1),
('10 ADVANCED HOCKEY DRILLS TO IMPROVE YOUR SKILLS', 'https://www.youtube.com/watch?v=OWEC-KSdmHw', 1, 2),
('50 Famous Goals ● Impossible To Forget', 'hhttps://www.youtube.com/watch?v=bKOTKHtbM54', 1, 2),
('Bachata Beginner Basic Steps Tutorial - Demetrio & Nicole - Bachata Dance Academy', 'https://www.youtube.com/watch?v=xhrdh-uFkog', 1, 3),
('Sara Lynn performs Tribal Fusion Belly Dance in FISSION', 'https://www.youtube.com/watch?v=Rh_82EHdD0E', 1, 3),
('Jade Chynoweth - "Baby Shark" | Aliya Janell Choreography', 'https://www.youtube.com/watch?v=hbfl4Rhsm3w', 1, 3),
('Bob Ross - Towering Peaks (Season 10 Episode 1)', 'https://www.youtube.com/watch?v=1s58rW0_LN4', 1, 4),
('Bob Ross - Northern Lights (Season 8 Episode 13)', 'https://www.youtube.com/watch?v=vgbMONXc9Cs', 1, 4),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 2, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 2, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 2, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 3, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 4, 1),
('EASIEST DIY Simple Birdhouse with Minimal Tools Step by Step | Ale''s Everyday', 'https://www.youtube.com/watch?v=BZwn6idcJE8', 4, 6),
('10 ADVANCED HOCKEY DRILLS TO IMPROVE YOUR SKILLS', 'https://www.youtube.com/watch?v=OWEC-KSdmHw', 5, 2),
('10 ADVANCED HOCKEY DRILLS TO IMPROVE YOUR SKILLS', 'https://www.youtube.com/watch?v=OWEC-KSdmHw', 5, 2),
('Bachata Beginner Basic Steps Tutorial - Demetrio & Nicole - Bachata Dance Academy', 'https://www.youtube.com/watch?v=xhrdh-uFkog', 5, 3),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 6, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 6, 1),
('Learn Java in 14 Minutes (seriously)', 'https://www.youtube.com/watch?v=RRubcjpTkks&ab_channel=AlexLee', 6, 1),
('Gordon''s Quick & Simple Recipes | Gordon Ramsay ', 'https://www.youtube.com/watch?v=mhDJNfV7hjk', 6, 5),
('EASIEST DIY Simple Birdhouse with Minimal Tools Step by Step | Ale s Everyday', 'https://www.youtube.com/watch?v=BZwn6idcJE8', 6, 6),
('EASIEST DIY Simple Birdhouse with Minimal Tools Step by Step | Ale s Everyday', 'https://www.youtube.com/watch?v=BZwn6idcJE8', 6, 6),
('EASIEST DIY Simple Birdhouse with Minimal Tools Step by Step | Ale s Everyday', 'https://www.youtube.com/watch?v=BZwn6idcJE8', 6, 6),
('EASIEST DIY Simple Birdhouse with Minimal Tools Step by Step | Ale s Everyday', 'https://www.youtube.com/watch?v=BZwn6idcJE8', 6, 6)