DROP TABLE IF EXISTS moments CASCADE;

CREATE TABLE moments(
  id SERIAL PRIMARY KEY NOT NULL,
  label VARCHAR(255) NOT NULL,
  start_time INTEGER NOT NULL,
  end_time INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE
);